import 'server-only'

import { createHash, randomBytes } from 'node:crypto'
import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises'
import path from 'node:path'

/**
 * Document storage (README §36, open question Q9).
 *
 * Q9's tabled default reads "S3-compatible, local disk fallback"; what is built
 * here is the reverse emphasis — **local disk first**, behind an interface an
 * S3 adapter drops into without touching a call site. Nothing above this module
 * knows where a file physically lives; it holds a `storageKey` string, which is
 * exactly what `Document.storageKey` is documented to be ("S3 key or relative
 * disk path"). When the hosting answer (Q7) lands, this file changes and
 * nothing else does.
 *
 * Files are deliberately **not** served from `public/`. A document attached to
 * a lead is visible to the people who can see that lead, and anything under
 * `public/` is visible to anyone who can guess the URL. Downloads go through a
 * route handler that re-checks visibility and then calls `read` below.
 */

export type StoredFile = {
  storageKey: string
  fileName: string
  mimeType: string
  sizeBytes: number
}

/** Uploads land here. Outside `public/` on purpose — see above. */
const ROOT = path.resolve(process.cwd(), 'storage', 'uploads')

/**
 * 10 MB. Large enough for a resume, a proposal deck or a signed contract scan;
 * small enough that a mistaken video upload fails fast rather than filling the
 * disk. Server actions have their own body limit, so this is the second of two
 * gates, not the only one.
 */
export const MAX_UPLOAD_BYTES = 10 * 1024 * 1024

/**
 * What a browser may be asked to render inline, and what we accept at all.
 *
 * An allow-list rather than a deny-list: the failure mode of guessing wrong is
 * a stored `text/html` file that executes as our own origin when opened. The
 * download route serves everything as an attachment regardless, so this is
 * defence in depth rather than the only control.
 */
const ALLOWED_MIME_TYPES = new Set([
  'application/pdf',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.ms-excel',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.ms-powerpoint',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'text/plain',
  'text/csv',
  'image/png',
  'image/jpeg',
  'image/gif',
  'image/webp',
  'application/zip',
])

export function isAllowedMimeType(mimeType: string): boolean {
  return ALLOWED_MIME_TYPES.has(mimeType)
}

/**
 * Extensions matching the MIME allow-list.
 *
 * Checked *as well as* the MIME type, because the type is whatever the browser
 * chose to send and a caller can send anything: a `.html` file declared as
 * `image/png` passes the MIME check on its own. Downloads are always served as
 * an attachment with `nosniff`, so this is the second of two locks rather than
 * the only one.
 */
const ALLOWED_EXTENSIONS = new Set([
  '.pdf',
  '.doc',
  '.docx',
  '.xls',
  '.xlsx',
  '.ppt',
  '.pptx',
  '.txt',
  '.csv',
  '.png',
  '.jpg',
  '.jpeg',
  '.gif',
  '.webp',
  '.zip',
])

export function isAllowedExtension(fileName: string): boolean {
  const extension = path.extname(fileName).toLowerCase()
  return extension !== '' && ALLOWED_EXTENSIONS.has(extension)
}

/**
 * Strip a client-supplied filename down to something safe to display and to
 * echo in a `Content-Disposition` header.
 *
 * The name is never used to build a path — `store` generates its own key — so
 * this is about display and header safety, not traversal. Quotes and control
 * characters would let a filename break out of the header it sits in.
 */
export function safeFileName(name: string): string {
  const base = path.basename(name).replace(/[\u0000-\u001f"\\]/g, '')
  const trimmed = base.trim()
  return trimmed === '' ? 'file' : trimmed.slice(0, 200)
}

/**
 * Where a file lives on disk, given its key.
 *
 * Keys are generated by `store` and never come from a user, but this still
 * refuses anything that escapes the root: the day a key does reach here from a
 * database row an attacker influenced, the answer must be a refusal rather than
 * `/etc/passwd`.
 */
function resolveKey(storageKey: string): string {
  const resolved = path.resolve(ROOT, storageKey)
  if (resolved !== ROOT && !resolved.startsWith(ROOT + path.sep)) {
    throw new Error('Storage key resolves outside the upload root.')
  }
  return resolved
}

/**
 * Write a file and return what the `Document` row needs.
 *
 * The key is `yyyy/mm/<random>.<ext>`: sharded by month so no single directory
 * accumulates every upload the company ever made, and random rather than named
 * after the file, so two people uploading `resume.pdf` cannot collide and
 * neither can guess the other's key.
 */
export async function store(file: File): Promise<StoredFile> {
  const fileName = safeFileName(file.name)

  // Re-checked here, not only in the calling action. `arrayBuffer()` pulls the
  // whole file into memory, so an oversized upload has to be refused *before*
  // that line rather than after it — and a second call site added in a later
  // phase (resumes in Phase 4, the importer in Phase 7) inherits the checks
  // instead of having to remember them.
  if (file.size > MAX_UPLOAD_BYTES) {
    throw new Error(`File exceeds the ${MAX_UPLOAD_BYTES} byte limit.`)
  }
  if (!isAllowedMimeType(file.type) || !isAllowedExtension(fileName)) {
    throw new Error(`File type not accepted: ${file.type || 'unknown'}`)
  }

  const bytes = Buffer.from(await file.arrayBuffer())
  const extension = path.extname(fileName).slice(0, 10).toLowerCase()

  const now = new Date()
  const folder = `${now.getFullYear()}/${String(now.getMonth() + 1).padStart(2, '0')}`
  const storageKey = `${folder}/${randomBytes(16).toString('hex')}${extension}`

  const destination = resolveKey(storageKey)
  await mkdir(path.dirname(destination), { recursive: true })
  await writeFile(destination, bytes)

  return {
    storageKey,
    fileName,
    mimeType: file.type || 'application/octet-stream',
    sizeBytes: bytes.byteLength,
  }
}

export function read(storageKey: string): Promise<Buffer> {
  return readFile(resolveKey(storageKey))
}

/**
 * Remove a stored file.
 *
 * A missing file is success: the caller's goal is that it is gone, and failing
 * a document deletion because the bytes were already removed would leave a row
 * nobody can clear.
 */
export async function remove(storageKey: string): Promise<void> {
  try {
    await unlink(resolveKey(storageKey))
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
  }
}

/** Weak validator for the download route's `ETag`. Content-addressed, so free. */
export function etagFor(bytes: Buffer): string {
  return `"${createHash('sha1').update(bytes).digest('hex')}"`
}

/** Human-readable size for the documents table. */
export function formatBytes(sizeBytes: number): string {
  if (sizeBytes < 1024) return `${sizeBytes} B`
  if (sizeBytes < 1024 * 1024) return `${Math.round(sizeBytes / 1024)} KB`
  return `${(sizeBytes / (1024 * 1024)).toFixed(1)} MB`
}
