import { can, pageAccess } from '@/lib/authz'
import { PERMISSIONS } from '@/lib/permissions'
import { currencySymbol } from '@/lib/settings'
import { formatMoney } from '@/lib/format'
import { formatCounterDate } from '@/lib/prospecting/dates'
import { formatRate, rate } from '@/lib/prospecting/metrics'
import {
  analyticsQuery,
  leadListHref,
  resolveAnalytics,
} from '@/lib/reports/filters'
import { filterOptions } from '@/lib/reports/options'
import { groupedPerformance, groupLabels, UNGROUPED } from '@/lib/reports/data/grouped'
import { AccessDenied } from '@/components/access-denied'
import { AnalyticsFilterBar } from '@/components/analytics-filters'
import { Bars } from '@/components/charts/bars'
import { ExportButtons } from '@/components/export-buttons'
import { Card, EmptyState, PageHeader } from '@/components/ui/page'
import { Table, TBody, TD, TH, THead, TR } from '@/components/ui/table'

export const metadata = { title: 'BDM conversion · Sales CRM' }

type SearchParams = Promise<Record<string, string | string[] | undefined>>

const number = (value: number) => value.toLocaleString('en-GB')

/**
 * BDM Conversion (README §28).
 *
 * The mirror of the BDE report, and the mirror is the point: this one groups by
 * `assignedToId` — who is *working* the deal — and its columns are about
 * progression rather than volume. Proposal and Negotiation are read from
 * `LeadStageHistory` (decision D12), so a deal that has been to Negotiation and
 * back still counts as having got there; reading them off the current stage would
 * credit only whatever happens to be true this morning.
 *
 * "Unassigned" is a row. A lead nobody owns is not converting, and hiding it
 * would make the win rates above it look better than the pipeline is.
 */
export default async function BdmReportPage({
  searchParams,
}: {
  searchParams: SearchParams
}) {
  const viewer = await pageAccess(PERMISSIONS.REPORT_PERFORMANCE)
  if (!viewer) return <AccessDenied what="performance reports" />

  const params = await searchParams
  const scope = await resolveAnalytics(viewer, params)

  const [rows, options, symbol, canSeeRevenue, canExport] = await Promise.all([
    groupedPerformance(scope, 'assignedToId', [
      'REQUIREMENT_GATHERING',
      'PROPOSAL',
      'NEGOTIATION',
      'WON',
    ]),
    filterOptions(viewer),
    currencySymbol(),
    can(viewer, PERMISSIONS.REPORT_REVENUE),
    can(viewer, PERMISSIONS.DATA_EXPORT),
  ])

  const labels = await groupLabels(
    'assignedToId',
    rows.map((row) => row.key),
  )

  const query = analyticsQuery({
    ...scope.filters,
    from: scope.range.fromKey,
    to: scope.range.toKey,
  })

  const totals = rows.reduce(
    (carry, row) => ({
      leads: carry.leads + row.counts.total,
      proposal: carry.proposal + (row.reached.PROPOSAL ?? 0),
      negotiation: carry.negotiation + (row.reached.NEGOTIATION ?? 0),
      won: carry.won + (row.reached.WON ?? 0),
      lost: carry.lost + row.counts.lost,
      pipeline: carry.pipeline + row.pipeline,
      wonRevenue: carry.wonRevenue + row.wonRevenue,
    }),
    {
      leads: 0,
      proposal: 0,
      negotiation: 0,
      won: 0,
      lost: 0,
      pipeline: 0,
      wonRevenue: 0,
    },
  )

  return (
    <div className="space-y-5">
      <PageHeader
        title="BDM conversion"
        description="Leads owned, how far each person moved them, and what closed."
        actions={
          canExport ? <ExportButtons report="bdm" query={query} /> : undefined
        }
      />

      <AnalyticsFilterBar
        action="/reports/bdm"
        filters={scope.filters}
        from={scope.range.fromKey}
        to={scope.range.toKey}
        options={options}
        // Grouped by assignee, so no assignee filter — same reasoning as the BDE
        // report. The "generated by" filter stays: "how well does this BDM
        // convert what that BDE sends them" is a real question.
        only={['vertical', 'source', 'bde', 'team', 'status', 'priority']}
      />

      <p className="text-xs text-slate-500">
        {formatCounterDate(scope.range.from)} to{' '}
        {formatCounterDate(scope.range.to)}. The Leads column counts leads
        created in the period; the stage columns count leads that passed through
        that stage in the period, whenever they were created. So a person can show
        more wins than leads — those are last quarter&apos;s deals closing now,
        which is exactly what a conversion report should show.
      </p>

      {rows.length === 0 ? (
        <EmptyState>No leads in this period.</EmptyState>
      ) : (
        <>
          <Card title="Per person">
            <Table>
              <THead>
                <TR>
                  <TH>Person</TH>
                  <TH className="text-right">Leads owned</TH>
                  <TH className="text-right">Requirement</TH>
                  <TH className="text-right">Proposal</TH>
                  <TH className="text-right">Negotiation</TH>
                  <TH className="text-right">Won</TH>
                  <TH className="text-right">Lost</TH>
                  <TH className="text-right">Negotiation → won</TH>
                  <TH className="text-right">Win rate</TH>
                  <TH className="text-right">Pipeline</TH>
                  {canSeeRevenue ? (
                    <TH className="text-right">Won revenue</TH>
                  ) : null}
                </TR>
              </THead>
              <TBody>
                {rows.map((row) => {
                  const negotiation = row.reached.NEGOTIATION ?? 0
                  const won = row.reached.WON ?? 0

                  return (
                    <TR key={row.key || 'unassigned'}>
                      <TD className="font-medium text-slate-900">
                        {row.key === UNGROUPED ? (
                          <span className="text-slate-500">Unassigned</span>
                        ) : (
                          <a
                            href={leadListHref(scope, { bdm: row.key })}
                            className="hover:underline"
                          >
                            {labels.get(row.key) ?? 'Former user'}
                          </a>
                        )}
                      </TD>
                      <TD className="text-right tabular-nums">
                        {number(row.counts.total)}
                      </TD>
                      <TD className="text-right tabular-nums">
                        {number(row.reached.REQUIREMENT_GATHERING ?? 0)}
                      </TD>
                      <TD className="text-right tabular-nums">
                        {number(row.reached.PROPOSAL ?? 0)}
                      </TD>
                      <TD className="text-right tabular-nums">
                        {number(negotiation)}
                      </TD>
                      <TD className="text-right tabular-nums">{number(won)}</TD>
                      <TD className="text-right tabular-nums">
                        {number(row.counts.lost)}
                      </TD>
                      <TD className="text-right tabular-nums">
                        {formatRate(rate(won, negotiation))}
                      </TD>
                      <TD className="text-right tabular-nums">
                        {formatRate(row.conversion)}
                      </TD>
                      <TD className="text-right tabular-nums">
                        {formatMoney(row.pipeline, symbol)}
                      </TD>
                      {canSeeRevenue ? (
                        <TD className="text-right tabular-nums">
                          {formatMoney(row.wonRevenue, symbol)}
                        </TD>
                      ) : null}
                    </TR>
                  )
                })}
              </TBody>
              <tfoot className="border-t border-slate-300 bg-slate-50 font-medium">
                <TR>
                  <TD className="text-slate-900">Everyone in scope</TD>
                  <TD className="text-right tabular-nums">
                    {number(totals.leads)}
                  </TD>
                  <TD />
                  <TD className="text-right tabular-nums">
                    {number(totals.proposal)}
                  </TD>
                  <TD className="text-right tabular-nums">
                    {number(totals.negotiation)}
                  </TD>
                  <TD className="text-right tabular-nums">
                    {number(totals.won)}
                  </TD>
                  <TD className="text-right tabular-nums">
                    {number(totals.lost)}
                  </TD>
                  <TD className="text-right tabular-nums">
                    {formatRate(rate(totals.won, totals.negotiation))}
                  </TD>
                  <TD className="text-right tabular-nums">
                    {formatRate(rate(totals.won, totals.won + totals.lost))}
                  </TD>
                  <TD className="text-right tabular-nums">
                    {formatMoney(totals.pipeline, symbol)}
                  </TD>
                  {canSeeRevenue ? (
                    <TD className="text-right tabular-nums">
                      {formatMoney(totals.wonRevenue, symbol)}
                    </TD>
                  ) : null}
                </TR>
              </tfoot>
            </Table>
          </Card>

          <Card
            title="Open pipeline value per person"
            description="What each person is currently carrying, at deal value or expected budget. As at today, whatever the date filter says."
          >
            <Bars
              bars={rows
                .map((row) => ({
                  key: row.key || 'unassigned',
                  label:
                    row.key === UNGROUPED
                      ? 'Unassigned'
                      : (labels.get(row.key) ?? 'Former user'),
                  value: Math.round(row.pipeline),
                  note: `${row.counts.open} open`,
                  href:
                    row.key === UNGROUPED
                      ? undefined
                      : leadListHref(scope, { bdm: row.key, status: 'OPEN' }),
                }))
                .sort((a, b) => b.value - a.value)}
            />
          </Card>
        </>
      )}
    </div>
  )
}
