import { ButtonLink } from '@/components/ui/button'
import { Select } from '@/components/ui/field'
import {
  COMMON_STAGE_LABELS,
  COMMON_STAGE_ORDER,
  LEAD_STATUS_LABELS,
  PRIORITY_LABELS,
  PRIORITY_ORDER,
} from '@/lib/leads/display'
import type { AnalyticsFilters } from '@/lib/reports/filters'
import type { FilterOptions } from '@/lib/reports/options'

/**
 * The global filter bar of docs/03 §1 — date range, vertical, source, BDE, BDM,
 * team, status — shared by the dashboard and all eleven reports.
 *
 * A plain GET form, like the narrower `ReportFilterBar` it sits beside: applying
 * a filter produces a URL. That is what makes README §37's drill-down chain work
 * at all, and what lets a Sales Head paste the view they are looking at into a
 * message and have the recipient see the same numbers (subject to their own data
 * scope, which no URL can widen).
 *
 * `only` exists because not every filter means something on every screen. The
 * BDE report is *grouped* by BDE, so offering a BDE filter there would be a
 * control that reduces its own table to one row; the payments report has no
 * priority to speak of. A screen names the filters it answers to rather than
 * showing seven and ignoring three.
 */

export type AnalyticsFilterKey =
  | 'vertical'
  | 'source'
  | 'bde'
  | 'bdm'
  | 'team'
  | 'status'
  | 'priority'

const ALL_KEYS: AnalyticsFilterKey[] = [
  'vertical',
  'source',
  'bde',
  'bdm',
  'team',
  'status',
  'priority',
]

export function AnalyticsFilterBar({
  action,
  filters,
  from,
  to,
  options,
  only,
  stage,
  hidden,
}: {
  action: string
  filters: AnalyticsFilters
  /** The resolved range, so the inputs show the default rather than blanks. */
  from: string
  to: string
  options: FilterOptions
  only?: AnalyticsFilterKey[]
  /**
   * Offer the common-stage filter too. Only the lead list consumes it, so it is
   * off unless a screen drills through with it.
   */
  stage?: string
  hidden?: Record<string, string>
}) {
  const keys = only ?? ALL_KEYS
  const shows = (key: AnalyticsFilterKey) => keys.includes(key)

  return (
    <form
      method="get"
      action={action}
      className="flex flex-wrap items-end gap-2 rounded-lg border border-slate-200 bg-white p-3"
    >
      {Object.entries(hidden ?? {}).map(([name, value]) => (
        <input key={name} type="hidden" name={name} value={value} />
      ))}
      {stage ? <input type="hidden" name="stage" value={stage} /> : null}

      <DateInput id="from" label="From" value={from} />
      <DateInput id="to" label="To" value={to} />

      {shows('vertical') ? (
        <FilterSelect
          id="vertical"
          label="Vertical"
          blank="All verticals"
          value={filters.vertical}
          options={options.verticals.map((row) => ({
            value: row.id,
            label: row.name,
          }))}
        />
      ) : null}

      {shows('source') ? (
        <FilterSelect
          id="source"
          label="Source"
          blank="All sources"
          value={filters.source}
          options={options.sources.map((row) => ({
            value: row.id,
            label: row.name,
          }))}
        />
      ) : null}

      {/* Two person filters, never one. README §6.3 keeps "generated by" and
          "assigned to" distinct for the whole application, and a single "person"
          filter here would silently pick one of them — crediting a BDM's
          conversion to the BDE who sourced the lead, or the reverse. */}
      {shows('bde') ? (
        <FilterSelect
          id="bde"
          label="Generated by"
          blank="Anyone"
          value={filters.bde}
          options={options.people.map((row) => ({
            value: row.id,
            label: row.name,
          }))}
        />
      ) : null}

      {shows('bdm') ? (
        <FilterSelect
          id="bdm"
          label="Assigned to"
          blank="Anyone"
          value={filters.bdm}
          options={options.people.map((row) => ({
            value: row.id,
            label: row.name,
          }))}
        />
      ) : null}

      {shows('team') ? (
        <FilterSelect
          id="team"
          label="Team"
          blank="All teams"
          value={filters.team}
          options={options.teams.map((row) => ({
            value: row.id,
            label: row.name,
          }))}
        />
      ) : null}

      {shows('status') ? (
        <FilterSelect
          id="status"
          label="Status"
          blank="Any status"
          value={filters.status}
          options={(['OPEN', 'WON', 'LOST'] as const).map((status) => ({
            value: status,
            label: LEAD_STATUS_LABELS[status],
          }))}
        />
      ) : null}

      {shows('priority') ? (
        <FilterSelect
          id="priority"
          label="Priority"
          blank="Any priority"
          value={filters.priority}
          options={PRIORITY_ORDER.map((priority) => ({
            value: priority,
            label: PRIORITY_LABELS[priority],
          }))}
        />
      ) : null}

      <button
        type="submit"
        className="h-9 rounded-md border border-slate-300 bg-white px-3.5 text-sm font-medium text-slate-700 transition hover:bg-slate-50"
      >
        Apply
      </button>
      <ButtonLink href={action} variant="ghost">
        Clear
      </ButtonLink>
    </form>
  )
}

/** The common-stage options, for screens that offer the lead list's stage filter. */
export const COMMON_STAGE_OPTIONS = COMMON_STAGE_ORDER.map((stage) => ({
  value: stage,
  label: COMMON_STAGE_LABELS[stage],
}))

function DateInput({
  id,
  label,
  value,
}: {
  id: string
  label: string
  value: string
}) {
  return (
    <div>
      <label
        htmlFor={id}
        className="mb-1 block text-xs font-medium text-slate-600"
      >
        {label}
      </label>
      <input
        id={id}
        name={id}
        type="date"
        defaultValue={value}
        className="h-9 rounded-md border border-slate-300 bg-white px-2.5 text-sm text-slate-900 shadow-xs"
      />
    </div>
  )
}

function FilterSelect({
  id,
  label,
  blank,
  value,
  options,
}: {
  id: string
  label: string
  blank: string
  value: string | undefined
  options: Array<{ value: string; label: string }>
}) {
  return (
    <div className="min-w-36">
      <label
        htmlFor={id}
        className="mb-1 block text-xs font-medium text-slate-600"
      >
        {label}
      </label>
      <Select id={id} name={id} defaultValue={value ?? ''}>
        <option value="">{blank}</option>
        {options.map((option) => (
          <option key={option.value} value={option.value}>
            {option.label}
          </option>
        ))}
      </Select>
    </div>
  )
}
