import { requireUser } from '@/lib/auth/session'
import { can } from '@/lib/authz'
import { PERMISSIONS } from '@/lib/permissions'
import { currencySymbol } from '@/lib/settings'
import { formatDate, formatMoney } from '@/lib/format'
import { PRIORITY_LABELS } from '@/lib/leads/display'
import { formatCounterDate } from '@/lib/prospecting/dates'
import { Card } from '@/components/ui/page'
import { ExternalLink } from '@/components/ui/external-link'
import { RowAction } from '@/components/row-action'
import { loadLead } from './lead'
import { deleteLeadAction } from '../actions'

type Params = Promise<{ id: string }>

export async function generateMetadata({ params }: { params: Params }) {
  const { id } = await params
  const viewer = await requireUser()
  const lead = await loadLead(viewer, id)
  return { title: `${lead.leadCode} · Sales CRM` }
}

export default async function LeadOverviewPage({ params }: { params: Params }) {
  const viewer = await requireUser()
  const { id } = await params
  const lead = await loadLead(viewer, id)

  const [symbol, canDelete] = await Promise.all([
    currencySymbol(),
    can(viewer, PERMISSIONS.LEAD_DELETE),
  ])

  return (
    <div className="grid gap-4 lg:grid-cols-2">
      <Card title="Requirement">
        <dl className="space-y-2 text-sm">
          <Fact label="Summary">{lead.title}</Fact>
          <Fact label="Description">
            {lead.requirementDescription ? (
              <span className="whitespace-pre-wrap">
                {lead.requirementDescription}
              </span>
            ) : (
              '—'
            )}
          </Fact>
          <Fact label="Service">{lead.service?.name ?? '—'}</Fact>
          <Fact label="Product">{lead.product?.name ?? '—'}</Fact>
          <Fact label="Source">{lead.source?.name ?? '—'}</Fact>
          <Fact label="Expected budget">
            {formatMoney(lead.expectedBudget, symbol)}
          </Fact>
          <Fact label="Deal value">{formatMoney(lead.dealValue, symbol)}</Fact>
          <Fact label="Timeline">{lead.expectedTimeline ?? '—'}</Fact>
          <Fact label="Priority">{PRIORITY_LABELS[lead.priority]}</Fact>
        </dl>
      </Card>

      <Card title="Client and contact">
        <dl className="space-y-2 text-sm">
          <Fact label="Company">
            <a
              href={`/clients/${lead.client.id}`}
              className="text-slate-800 underline hover:text-slate-900"
            >
              {lead.client.clientName}
            </a>
            <span className="text-slate-500"> · {lead.client.clientCode}</span>
          </Fact>
          <Fact label="Country">{lead.client.country?.name ?? '—'}</Fact>
          <Fact label="Contact">
            {lead.primaryContact ? (
              <>
                {lead.primaryContact.name}
                {lead.primaryContact.designation
                  ? ` — ${lead.primaryContact.designation}`
                  : ''}
              </>
            ) : (
              'Not set'
            )}
          </Fact>
          <Fact label="Email">{lead.primaryContact?.email ?? '—'}</Fact>
          <Fact label="Phone">{lead.primaryContact?.phone ?? '—'}</Fact>
        </dl>
      </Card>

      <Card title="Ownership and dates">
        <dl className="space-y-2 text-sm">
          <Fact label="Generated by">{lead.generatedBy.name}</Fact>
          <Fact label="Assigned to">{lead.assignedTo?.name ?? 'Unassigned'}</Fact>
          <Fact label="Team">{lead.team?.name ?? '—'}</Fact>
          <Fact label="Created">
            {formatDate(lead.createdAt)} by {lead.createdBy.name}
          </Fact>
          <Fact label="Next follow-up">{formatDate(lead.nextFollowUpAt)}</Fact>
          <Fact label="Expected close">{formatDate(lead.expectedCloseDate)}</Fact>
          <Fact label="Closed">{formatDate(lead.closedAt)}</Fact>
        </dl>
      </Card>

      <Card title="Additional information">
        <dl className="space-y-2 text-sm">
          <Fact label="Campaign">{lead.campaignName ?? '—'}</Fact>
          <Fact label="Came from">
            {lead.sourceActivity ? (
              <>
                {lead.sourceActivity.metric.label} ·{' '}
                {formatCounterDate(lead.sourceActivity.activityDate)} ·{' '}
                {lead.sourceActivity.count} logged by{' '}
                {lead.sourceActivity.user.name}
              </>
            ) : (
              '—'
            )}
          </Fact>
          <Fact label="Reference">
            <ExternalLink href={lead.referenceUrl} />
          </Fact>
          <Fact label="Notes">
            {lead.additionalNotes ? (
              <span className="whitespace-pre-wrap">{lead.additionalNotes}</span>
            ) : (
              '—'
            )}
          </Fact>
        </dl>

        {canDelete ? (
          <div className="mt-4 border-t border-slate-100 pt-3">
            <RowAction
              action={deleteLeadAction}
              id={lead.id}
              label="Delete lead"
              confirmMessage={`Delete ${lead.leadCode}? It is hidden rather than removed — its stage history survives and an administrator can restore it.`}
            />
          </div>
        ) : null}
      </Card>
    </div>
  )
}

function Fact({
  label,
  children,
}: {
  label: string
  children: React.ReactNode
}) {
  return (
    <div className="flex gap-3">
      <dt className="w-32 shrink-0 text-slate-500">{label}</dt>
      <dd className="min-w-0 flex-1 break-words text-slate-800">{children}</dd>
    </div>
  )
}
