import { prisma } from '@/lib/db'
import { getCurrentUser } from '@/lib/auth/session'
import { can } from '@/lib/authz'
import { recordAudit } from '@/lib/audit/record'
import { PERMISSIONS } from '@/lib/permissions'
import { csvResponse, toCsv } from '@/lib/csv'
import { COMMON_STAGE_LABELS, LEAD_STATUS_LABELS } from '@/lib/leads/display'
import { leadFilterQuery, leadWhere, pickLeadFilters } from '../filters'

/**
 * CSV export of the lead list.
 *
 * Re-parses the request's own query string through `pickLeadFilters` and
 * `leadWhere`, the same two functions the list page uses. That is the point:
 * an export built from a second, parallel query is an export that quietly
 * stops matching what the person was looking at when they clicked it — and
 * `leadWhere` is also where the visibility scope is applied, so a divergent
 * implementation is a data-leak waiting to happen.
 */

/**
 * A cap, not a page size. Ten thousand rows is far past what anyone reads in a
 * spreadsheet and comfortably past the assumed monthly volume (open question
 * Q5); it exists so a mistaken unfiltered export cannot pull the whole table
 * into memory. The footer row says when it bit.
 */
const EXPORT_LIMIT = 10_000

export async function GET(request: Request) {
  const user = await getCurrentUser()
  if (!user) return new Response('Unauthorised', { status: 401 })

  if (!(await can(user, PERMISSIONS.DATA_EXPORT))) {
    return new Response('Forbidden', { status: 403 })
  }

  const params = Object.fromEntries(new URL(request.url).searchParams)
  const filters = pickLeadFilters(params)
  const where = await leadWhere(user, filters)

  const leads = await prisma.lead.findMany({
    where,
    select: {
      leadCode: true,
      title: true,
      status: true,
      commonStage: true,
      priority: true,
      expectedBudget: true,
      dealValue: true,
      expectedTimeline: true,
      createdAt: true,
      stageChangedAt: true,
      closedAt: true,
      nextFollowUpAt: true,
      expectedCloseDate: true,
      campaignName: true,
      referenceUrl: true,
      client: { select: { clientCode: true, clientName: true, country: { select: { name: true } } } },
      primaryContact: { select: { name: true, email: true, phone: true } },
      vertical: { select: { name: true } },
      source: { select: { name: true } },
      service: { select: { name: true } },
      product: { select: { name: true } },
      currentStage: { select: { name: true } },
      generatedBy: { select: { name: true } },
      assignedTo: { select: { name: true } },
      team: { select: { name: true } },
      lostReason: { select: { name: true } },
    },
    orderBy: { createdAt: 'desc' },
    take: EXPORT_LIMIT,
  })

  const body = toCsv(leads, [
    { header: 'Lead code', value: (lead) => lead.leadCode },
    { header: 'Requirement', value: (lead) => lead.title },
    { header: 'Client code', value: (lead) => lead.client.clientCode },
    { header: 'Client', value: (lead) => lead.client.clientName },
    { header: 'Country', value: (lead) => lead.client.country?.name },
    { header: 'Contact', value: (lead) => lead.primaryContact?.name },
    { header: 'Contact email', value: (lead) => lead.primaryContact?.email },
    { header: 'Contact phone', value: (lead) => lead.primaryContact?.phone },
    { header: 'Vertical', value: (lead) => lead.vertical.name },
    { header: 'Source', value: (lead) => lead.source?.name },
    { header: 'Service', value: (lead) => lead.service?.name },
    { header: 'Product', value: (lead) => lead.product?.name },
    { header: 'Stage', value: (lead) => lead.currentStage?.name },
    {
      header: 'Common stage',
      value: (lead) => COMMON_STAGE_LABELS[lead.commonStage],
    },
    { header: 'Status', value: (lead) => LEAD_STATUS_LABELS[lead.status] },
    { header: 'Priority', value: (lead) => lead.priority },
    { header: 'Generated by', value: (lead) => lead.generatedBy.name },
    { header: 'Assigned to', value: (lead) => lead.assignedTo?.name },
    { header: 'Team', value: (lead) => lead.team?.name },
    { header: 'Expected budget', value: (lead) => lead.expectedBudget?.toString() },
    { header: 'Deal value', value: (lead) => lead.dealValue?.toString() },
    { header: 'Expected timeline', value: (lead) => lead.expectedTimeline },
    { header: 'Lost reason', value: (lead) => lead.lostReason?.name },
    { header: 'Campaign', value: (lead) => lead.campaignName },
    { header: 'Reference URL', value: (lead) => lead.referenceUrl },
    { header: 'Created', value: (lead) => lead.createdAt },
    { header: 'Stage changed', value: (lead) => lead.stageChangedAt },
    { header: 'Next follow-up', value: (lead) => lead.nextFollowUpAt },
    { header: 'Expected close', value: (lead) => lead.expectedCloseDate },
    { header: 'Closed', value: (lead) => lead.closedAt },
  ])

  // `AuditAction.EXPORT` exists for exactly this: taking a copy of customer and
  // contact data out of the system is not a row change, so the ORM writer never
  // sees it, but it is one of the events a trail is kept for.
  await recordAudit({
    entityType: 'LEAD',
    entityId: 'export',
    action: 'EXPORT',
    fieldName: '(lead list)',
    newValue: `${leads.length} row(s); filters=${leadFilterQuery(filters) || '(none)'}`,
    userId: user.id,
  })

  return csvResponse(body, 'leads')
}
