import 'server-only'

import { prisma } from '@/lib/db'
import { PERMISSIONS, type Permission } from '@/lib/permissions'
import { formatCounterDate } from '@/lib/prospecting/dates'
import {
  buildFunnel,
  counterTotals,
  leadsCreatedByVertical,
  rate,
  reachedByStage,
} from '@/lib/prospecting/metrics'
import {
  pickReportFilters,
  resolvePeople,
  resolveRange,
} from '@/lib/prospecting/filters'
import {
  byCode,
  CANDIDATE_STAGE_CODES,
  candidatesSourced,
  interviewAndPlacementTotals,
  reachedFor,
  REQUIREMENT_STAGE_CODES,
  requirementReachedByStage,
  requirementsWithActivity,
  requirementTotals,
  subReachedByStage,
} from '@/lib/staffing/metrics'
import {
  reachedByCommonStage,
  reachedByVertical,
} from '@/lib/reports/aggregate'
import {
  peopleScopeOf,
  resolveAnalytics,
  resolveDashboard,
  type AnalyticsScope,
} from '@/lib/reports/filters'
import {
  conversion,
  leadCounts,
  pipelineValue,
  revenueTotals,
} from '@/lib/reports/kpis'
import {
  leadTriggerLabel,
  leadTriggerMetric,
  verticalsWithStages,
} from '@/lib/reports/options'
import {
  counterTotalsByPerson,
  groupedPerformance,
  groupLabels,
  UNGROUPED,
} from '@/lib/reports/data/grouped'
import { loadAging } from '@/lib/reports/data/aging'
import { loadWonLost } from '@/lib/reports/data/won-lost'
import { loadPayments } from '@/lib/reports/data/payments'
import { loadDemos } from '@/lib/reports/data/demos'
import {
  COMMON_STAGE_LABELS,
  LEAD_STATUS_LABELS,
  PRIORITY_LABELS,
} from '@/lib/leads/display'
import {
  DEMO_STATUS_LABELS,
  INVOICE_STATUS_LABELS,
} from '@/lib/commercials/display'
import type { ReportTable } from '@/lib/reports/table'
import type { CurrentUser } from '@/lib/auth/session'
import type { CommonStage, LeadStatus, Priority } from '@/generated/prisma/enums'

/**
 * The eleven reports, as data.
 *
 * Each entry says what a report is called, what permission it sits behind, and
 * how to turn a request's query string into a `ReportTable`. The export route is
 * then one route handler for every report and every format, and — the part that
 * matters — each `build` calls **the same loader the screen calls, with the same
 * parameters**, so the file cannot drift from the page. Phase 2's lead export
 * established that rule; this is it applied eleven times without eleven routes.
 *
 * The two Phase 3/4 reports are here too. Their screens parse the narrower
 * prospecting filter set (`user` rather than `bde`/`bdm`), so their builders
 * parse it as well rather than pretending everything shares one vocabulary — the
 * export link on those pages carries their own query string, and both halves
 * agree because both call `pickReportFilters`.
 */

type Params = Record<string, string | string[] | undefined>

export type ReportDefinition = {
  key: string
  title: string
  permission: Permission
  /** File name stem: `lead-source-2026-08-17.xlsx`. */
  basename: string
  build: (viewer: CurrentUser, params: Params) => Promise<ReportTable>
}

const number = (value: number) => value

/**
 * The filter set as label/value pairs, for the export's own header block.
 *
 * A file outlives the URL that made it. Without the period and the filters
 * printed on it, "Won revenue 412,000" in an email six weeks later is a number
 * with no question attached — so every export carries them, resolved to names
 * rather than left as ids nobody can read.
 */
async function analyticsMeta(
  scope: AnalyticsScope,
): Promise<Array<[string, string]>> {
  const [vertical, source, bde, bdm, team] = await Promise.all([
    scope.verticalId
      ? prisma.salesVertical.findUnique({
          where: { id: scope.verticalId },
          select: { name: true },
        })
      : null,
    scope.sourceId
      ? prisma.leadSource.findUnique({
          where: { id: scope.sourceId },
          select: { name: true },
        })
      : null,
    scope.bde
      ? prisma.user.findUnique({
          where: { id: scope.bde },
          select: { name: true },
        })
      : null,
    scope.bdm
      ? prisma.user.findUnique({
          where: { id: scope.bdm },
          select: { name: true },
        })
      : null,
    scope.teamId
      ? prisma.team.findUnique({
          where: { id: scope.teamId },
          select: { name: true },
        })
      : null,
  ])

  const meta: Array<[string, string]> = [
    [
      'Period',
      `${formatCounterDate(scope.range.from)} to ${formatCounterDate(scope.range.to)}`,
    ],
    ['Vertical', vertical?.name ?? 'All verticals'],
    ['Source', source?.name ?? 'All sources'],
    ['Generated by', bde?.name ?? 'Anyone'],
    ['Assigned to', bdm?.name ?? 'Anyone'],
    ['Team', team?.name ?? 'All teams'],
    [
      'Status',
      scope.status ? LEAD_STATUS_LABELS[scope.status as LeadStatus] : 'Any',
    ],
    [
      'Priority',
      scope.priority
        ? PRIORITY_LABELS[scope.priority as Priority]
        : 'Any',
    ],
  ]

  return meta
}

// ---------------------------------------------------------------------------
// Builders
// ---------------------------------------------------------------------------

async function buildVertical(
  viewer: CurrentUser,
  params: Params,
): Promise<ReportTable> {
  const scope = await resolveAnalytics(viewer, params)

  const [rows, verticals, revenue, meta] = await Promise.all([
    groupedPerformance(scope, 'verticalId', ['WON']),
    verticalsWithStages(),
    revenueTotals(scope),
    analyticsMeta(scope),
  ])

  const counters = await counterTotals(
    scope.range,
    peopleScopeOf(scope),
    scope.verticalId,
  )

  const byKey = new Map(rows.map((row) => [row.key, row]))
  const listed = verticals.filter(
    (vertical) => scope.verticalId === null || vertical.id === scope.verticalId,
  )

  return {
    title: 'Vertical performance',
    subtitle:
      'Leads are counted by creation date; Won by the date the lead reached its winning stage. Pipeline and Pending are as at today. The input column is not totalled — pitches, calls and campaigns are different units.',
    meta,
    columns: [
      { header: 'Vertical', width: 22 },
      { header: 'Input metric', width: 22 },
      { header: 'Input', format: 'number' },
      { header: 'Leads', format: 'number' },
      { header: 'Bridge %', format: 'percent' },
      { header: 'Open', format: 'number' },
      { header: 'Won', format: 'number' },
      { header: 'Lost', format: 'number' },
      { header: 'Won ÷ leads %', format: 'percent' },
      { header: 'Pipeline', format: 'money', width: 16 },
      { header: 'Won revenue', format: 'money', width: 16 },
      { header: 'Collected', format: 'money', width: 16 },
      { header: 'Pending', format: 'money', width: 16 },
    ],
    rows: listed.map((vertical) => {
      const row = byKey.get(vertical.id)
      const money = revenue.byVertical.get(vertical.id)
      const trigger = leadTriggerMetric(vertical.metrics)
      const input = trigger.metric
        ? (counters.get(trigger.metric.id) ?? 0)
        : null
      const leads = row?.counts.total ?? 0
      const won = row?.reached.WON ?? 0

      return [
        vertical.name,
        leadTriggerLabel(trigger),
        input,
        number(leads),
        input === null ? null : rate(leads, input),
        row?.counts.open ?? 0,
        won,
        row?.counts.lost ?? 0,
        rate(won, leads),
        row?.pipeline ?? 0,
        row?.wonRevenue ?? 0,
        money?.collected ?? 0,
        money?.pending ?? 0,
      ]
    }),
  }
}

async function buildLeadSource(
  viewer: CurrentUser,
  params: Params,
): Promise<ReportTable> {
  const scope = await resolveAnalytics(viewer, params)
  const [rows, meta] = await Promise.all([
    groupedPerformance(scope, 'sourceId', ['WON']),
    analyticsMeta(scope),
  ])
  const labels = await groupLabels(
    'sourceId',
    rows.map((row) => row.key),
  )

  return {
    title: 'Lead source performance',
    subtitle:
      '"No source recorded" is a row rather than an omission — it is often the largest one, and that is the finding. Conversion is won ÷ (won + lost), which ignores deals still open.',
    meta,
    columns: [
      { header: 'Source', width: 26 },
      { header: 'Leads', format: 'number' },
      { header: 'Open', format: 'number' },
      { header: 'Won', format: 'number' },
      { header: 'Lost', format: 'number' },
      { header: 'Won ÷ leads %', format: 'percent' },
      { header: 'Conversion %', format: 'percent' },
      { header: 'Pipeline', format: 'money', width: 16 },
      { header: 'Won revenue', format: 'money', width: 16 },
    ],
    rows: rows.map((row) => [
      row.key === UNGROUPED
        ? 'No source recorded'
        : (labels.get(row.key) ?? 'Retired source'),
      row.counts.total,
      row.counts.open,
      row.reached.WON ?? 0,
      row.counts.lost,
      rate(row.reached.WON ?? 0, row.counts.total),
      row.conversion,
      row.pipeline,
      row.wonRevenue,
    ]),
  }
}

async function buildBde(
  viewer: CurrentUser,
  params: Params,
): Promise<ReportTable> {
  const scope = await resolveAnalytics(viewer, params)
  const [rows, counters, meta] = await Promise.all([
    groupedPerformance(scope, 'generatedById', ['WON']),
    counterTotalsByPerson(scope),
    analyticsMeta(scope),
  ])

  const keys = new Set([...rows.map((row) => row.key), ...counters.keys()])
  const labels = await groupLabels('generatedById', [...keys])

  const people = [...keys]
    .map((key) => {
      const row = rows.find((candidate) => candidate.key === key)
      const logged = counters.get(key) ?? 0
      const leads = row?.counts.total ?? 0

      return {
        name: labels.get(key) ?? 'Former user',
        logged,
        leads,
        open: row?.counts.open ?? 0,
        won: row?.reached.WON ?? 0,
        lost: row?.counts.lost ?? 0,
        conversion: row?.conversion ?? null,
        pipeline: row?.pipeline ?? 0,
        wonRevenue: row?.wonRevenue ?? 0,
        bridge: logged > 0 ? rate(leads, logged) : null,
      }
    })
    .sort((a, b) => b.leads - a.leads || b.logged - a.logged)

  return {
    title: 'BDE lead generation',
    subtitle:
      'Grouped by whoever generated the lead, never by assignee. Counters are dated by the day the work was logged and leads by the day they were created, so the bridge percentage is an approximation across the month boundary.',
    meta,
    columns: [
      { header: 'Person', width: 24 },
      { header: 'Counters logged', format: 'number', width: 16 },
      { header: 'Leads generated', format: 'number', width: 16 },
      { header: 'Bridge %', format: 'percent' },
      { header: 'Open', format: 'number' },
      { header: 'Won', format: 'number' },
      { header: 'Lost', format: 'number' },
      { header: 'Conversion %', format: 'percent' },
      { header: 'Pipeline', format: 'money', width: 16 },
      { header: 'Won revenue', format: 'money', width: 16 },
    ],
    rows: people.map((person) => [
      person.name,
      person.logged === 0 ? null : person.logged,
      person.leads,
      person.bridge,
      person.open,
      person.won,
      person.lost,
      person.conversion,
      person.pipeline,
      person.wonRevenue,
    ]),
    footer: [
      'Everyone in scope',
      people.reduce((sum, person) => sum + person.logged, 0),
      people.reduce((sum, person) => sum + person.leads, 0),
      null,
      people.reduce((sum, person) => sum + person.open, 0),
      people.reduce((sum, person) => sum + person.won, 0),
      people.reduce((sum, person) => sum + person.lost, 0),
      null,
      people.reduce((sum, person) => sum + person.pipeline, 0),
      people.reduce((sum, person) => sum + person.wonRevenue, 0),
    ],
  }
}

async function buildBdm(
  viewer: CurrentUser,
  params: Params,
): Promise<ReportTable> {
  const scope = await resolveAnalytics(viewer, params)
  const stages: CommonStage[] = [
    'REQUIREMENT_GATHERING',
    'PROPOSAL',
    'NEGOTIATION',
    'WON',
  ]

  const [rows, meta] = await Promise.all([
    groupedPerformance(scope, 'assignedToId', stages),
    analyticsMeta(scope),
  ])
  const labels = await groupLabels(
    'assignedToId',
    rows.map((row) => row.key),
  )

  return {
    title: 'BDM conversion',
    subtitle:
      'Leads owned counts leads created in the period; the stage columns count leads that passed through that stage in the period, whenever they were created. So a person can show more wins than leads — those are earlier deals closing now.',
    meta,
    columns: [
      { header: 'Person', width: 24 },
      { header: 'Leads owned', format: 'number', width: 14 },
      { header: 'Requirement', format: 'number', width: 14 },
      { header: 'Proposal', format: 'number' },
      { header: 'Negotiation', format: 'number', width: 14 },
      { header: 'Won', format: 'number' },
      { header: 'Lost', format: 'number' },
      { header: 'Negotiation → won %', format: 'percent', width: 20 },
      { header: 'Win rate %', format: 'percent' },
      { header: 'Pipeline', format: 'money', width: 16 },
      { header: 'Won revenue', format: 'money', width: 16 },
    ],
    rows: rows.map((row) => [
      row.key === UNGROUPED
        ? 'Unassigned'
        : (labels.get(row.key) ?? 'Former user'),
      row.counts.total,
      row.reached.REQUIREMENT_GATHERING ?? 0,
      row.reached.PROPOSAL ?? 0,
      row.reached.NEGOTIATION ?? 0,
      row.reached.WON ?? 0,
      row.counts.lost,
      rate(row.reached.WON ?? 0, row.reached.NEGOTIATION ?? 0),
      row.conversion,
      row.pipeline,
      row.wonRevenue,
    ]),
  }
}

async function buildAging(
  viewer: CurrentUser,
  params: Params,
): Promise<ReportTable> {
  const scope = await resolveAnalytics(viewer, params)
  const [report, meta] = await Promise.all([
    loadAging(scope),
    analyticsMeta(scope),
  ])

  return {
    title: 'Pipeline aging',
    subtitle: `Open leads past the threshold configured for their own stage, as at today — the date range does not apply to this list. ${report.flagged} of ${report.openLeads} open leads are flagged.${
      report.truncated ? ' The comparison ran on the oldest 1,000 open leads.' : ''
    }`,
    meta,
    columns: [
      { header: 'Lead', width: 14 },
      { header: 'Requirement', width: 30 },
      { header: 'Client', width: 24 },
      { header: 'Vertical', width: 18 },
      { header: 'Stage', width: 20 },
      { header: 'Owner', width: 20 },
      { header: 'Generated by', width: 20 },
      { header: 'Priority', width: 12 },
      { header: 'Days in stage', format: 'number', width: 14 },
      { header: 'Threshold', format: 'number', width: 12 },
      { header: 'Over by', format: 'number', width: 12 },
      { header: 'Value', format: 'money', width: 16 },
    ],
    rows: report.leads.map((lead) => [
      lead.leadCode,
      lead.title,
      lead.client,
      lead.vertical,
      lead.stage,
      lead.owner ?? 'Unassigned',
      lead.generatedBy,
      PRIORITY_LABELS[lead.priority],
      lead.days,
      lead.threshold,
      lead.over,
      lead.value,
    ]),
  }
}

async function buildWonLost(
  viewer: CurrentUser,
  params: Params,
): Promise<ReportTable> {
  const scope = await resolveAnalytics(viewer, params)
  const [report, verticals, meta] = await Promise.all([
    loadWonLost(scope),
    verticalsWithStages(),
    analyticsMeta(scope),
  ])

  const names = new Map(verticals.map((vertical) => [vertical.id, vertical.name]))

  // One file, two tables: the outcome per vertical, then the lost reasons. They
  // are stacked into one sheet with a labelled first column rather than split
  // across sheets, because a reader scanning a PDF should not have to turn a page
  // to find out why the losses happened.
  const rows: ReportTable['rows'] = [
    ...report.byVertical.map((row) => [
      'Vertical',
      names.get(row.verticalId) ?? 'Retired vertical',
      row.won,
      row.lost,
      row.winRate,
      null,
    ]),
    ...report.reasons.map((reason) => [
      'Lost reason',
      reason.name,
      null,
      reason.count,
      reason.share,
      reason.value,
    ]),
  ]

  return {
    title: 'Won / lost analysis',
    subtitle: `Deals decided in this period, by close date — a lead created in May and lost in August belongs to August here and to May on the dashboard. Average sales cycle: ${
      report.cycle.won === null ? 'no wins' : `${report.cycle.won.toFixed(1)} days to win`
    }, ${
      report.cycle.lost === null ? 'no losses' : `${report.cycle.lost.toFixed(1)} days to loss`
    }.`,
    meta,
    columns: [
      { header: 'Breakdown', width: 14 },
      { header: 'Name', width: 30 },
      { header: 'Won', format: 'number' },
      { header: 'Lost / count', format: 'number', width: 14 },
      { header: 'Win rate / share %', format: 'percent', width: 18 },
      { header: 'At stake', format: 'money', width: 16 },
    ],
    rows,
    footer: [
      'Total',
      'Deals decided',
      report.won,
      report.lost,
      report.winRate,
      report.lostValue,
    ],
  }
}

async function buildRevenue(
  viewer: CurrentUser,
  params: Params,
): Promise<ReportTable> {
  const scope = await resolveAnalytics(viewer, params)
  const [revenue, pipeline, verticals, meta] = await Promise.all([
    revenueTotals(scope),
    pipelineValue(scope),
    verticalsWithStages(),
    analyticsMeta(scope),
  ])

  const listed = verticals.filter(
    (vertical) => scope.verticalId === null || vertical.id === scope.verticalId,
  )

  return {
    title: 'Revenue',
    subtitle:
      'Won and Collected are flows, dated by the day the deal closed or the money arrived. Pipeline, Invoiced and Pending are stocks, as at today, and do not move with the date range.',
    meta,
    columns: [
      { header: 'Vertical', width: 22 },
      { header: 'Pipeline', format: 'money', width: 16 },
      { header: 'Won', format: 'money', width: 16 },
      { header: 'Collected', format: 'money', width: 16 },
      { header: 'Pending', format: 'money', width: 16 },
      { header: 'Collected ÷ won %', format: 'percent', width: 18 },
      { header: 'Revenue rule', width: 26 },
    ],
    rows: listed.map((vertical) => {
      const money = revenue.byVertical.get(vertical.id)
      const won = money?.won ?? 0

      return [
        vertical.name,
        pipeline.byVertical.get(vertical.id) ?? 0,
        won,
        money?.collected ?? 0,
        money?.pending ?? 0,
        won > 0 ? rate(money?.collected ?? 0, won) : null,
        `${vertical.usesRequirements ? 'Placements' : 'Deal value on won leads'}${
          vertical.usesInvoicing ? '' : ' · invoicing off'
        }`,
      ]
    }),
    footer: [
      'All verticals',
      pipeline.total,
      revenue.totals.won,
      revenue.totals.collected,
      revenue.totals.pending,
      revenue.totals.won > 0
        ? rate(revenue.totals.collected, revenue.totals.won)
        : null,
      `Invoiced ${revenue.totals.invoiced.toFixed(2)}; overdue ${revenue.totals.overdue.toFixed(2)}`,
    ],
  }
}

async function buildPayments(
  viewer: CurrentUser,
  params: Params,
): Promise<ReportTable> {
  const scope = await resolveAnalytics(viewer, params)
  const [report, meta] = await Promise.all([
    loadPayments(scope),
    analyticsMeta(scope),
  ])

  return {
    title: 'Payment status',
    subtitle: `Invoices raised in this period, with the status each carries as at today. Outstanding across all dates: ${report.outstanding.pending.toFixed(
      2,
    )}, of which ${report.outstanding.overdue.toFixed(2)} is overdue. Ageing: ${report.ageing
      .map((bucket) => `${bucket.label} ${bucket.count}`)
      .join(', ')}.`,
    meta,
    columns: [
      { header: 'Invoice', width: 16 },
      { header: 'Client', width: 26 },
      { header: 'Lead', width: 14 },
      { header: 'Vertical', width: 18 },
      { header: 'Raised', format: 'date', width: 14 },
      { header: 'Due', format: 'date', width: 14 },
      { header: 'Total', format: 'money', width: 16 },
      { header: 'Received', format: 'money', width: 16 },
      { header: 'Owed', format: 'money', width: 16 },
      { header: 'Status', width: 16 },
      { header: 'Days late', format: 'number', width: 12 },
    ],
    rows: report.rows.map((row) => [
      row.invoiceNumber,
      row.client,
      row.leadCode,
      row.vertical,
      row.invoiceDate,
      row.dueDate,
      row.total,
      row.received,
      row.pending,
      INVOICE_STATUS_LABELS[row.status],
      row.daysOverdue > 0 ? row.daysOverdue : null,
    ]),
    footer: [
      'Live invoices raised in period',
      null,
      null,
      null,
      null,
      null,
      report.raised.total,
      report.raised.collected,
      report.raised.pending,
      `${report.raised.count} invoices`,
      null,
    ],
  }
}

async function buildDemos(
  viewer: CurrentUser,
  params: Params,
): Promise<ReportTable> {
  const scope = await resolveAnalytics(viewer, params)
  const [report, meta] = await Promise.all([
    loadDemos(scope),
    analyticsMeta(scope),
  ])

  return {
    title: 'Product demos',
    subtitle: `Demos are dated by when they were scheduled. Demo → proposal divides by leads with a completed demo, not by demos held. Demos by outcome: ${
      report.byStatus
        .map(([status, count]) => `${DEMO_STATUS_LABELS[status]} ${count}`)
        .join(', ') || 'none in this period'
    }.`,
    meta,
    columns: [
      { header: 'Vertical', width: 22 },
      { header: 'Inquiries', format: 'number', width: 12 },
      { header: 'Demos scheduled', format: 'number', width: 16 },
      { header: 'Demos completed', format: 'number', width: 16 },
      { header: 'Leads with a demo', format: 'number', width: 18 },
      { header: 'Inquiry → demo %', format: 'percent', width: 16 },
      { header: 'Proposal', format: 'number' },
      { header: 'Demo → proposal %', format: 'percent', width: 18 },
      { header: 'Negotiation', format: 'number', width: 14 },
      { header: 'Won', format: 'number' },
      { header: 'Inquiry → won %', format: 'percent', width: 16 },
      { header: 'Order value', format: 'money', width: 16 },
      { header: 'Average order', format: 'money', width: 16 },
    ],
    rows: report.rows.map((row) => [
      row.vertical,
      row.inquiries,
      row.scheduled,
      row.completed,
      row.leadsWithDemo,
      row.inquiryToDemo,
      row.reachedProposal,
      row.demoToProposal,
      row.reachedNegotiation,
      row.won,
      row.inquiryToWon,
      row.orderValue,
      row.averageOrderValue,
    ]),
    footer: [
      'All verticals',
      report.totals.inquiries,
      report.totals.scheduled,
      report.totals.completed,
      null,
      null,
      null,
      null,
      null,
      report.totals.won,
      null,
      report.totals.orderValue,
      report.totals.averageOrderValue,
    ],
  }
}

/**
 * The vertical funnel, exported.
 *
 * Parses the *prospecting* filter set, because that is what its screen parses —
 * one vertical at a time, one person filter called `user`. Both halves calling
 * `pickReportFilters` is what keeps the file and the page in step.
 */
async function buildFunnelTable(
  viewer: CurrentUser,
  params: Params,
): Promise<ReportTable> {
  const filters = pickReportFilters(params)
  const range = resolveRange(filters)
  const people = await resolvePeople(viewer, filters)

  const verticals = await prisma.salesVertical.findMany({
    where: { isActive: true },
    select: {
      id: true,
      name: true,
      metrics: {
        where: { isActive: true },
        select: { id: true, key: true, label: true, isLeadTrigger: true },
        orderBy: { sortOrder: 'asc' },
      },
      stages: {
        where: { isActive: true },
        select: { id: true, code: true, name: true, isWon: true, isLost: true },
        orderBy: { sortOrder: 'asc' },
      },
    },
    orderBy: { sortOrder: 'asc' },
  })

  const vertical =
    verticals.find((row) => row.id === filters.vertical) ?? verticals[0]

  if (!vertical) {
    return {
      title: 'Vertical funnel',
      columns: [{ header: 'Step' }],
      rows: [],
      meta: [['Period', `${formatCounterDate(range.from)} to ${formatCounterDate(range.to)}`]],
    }
  }

  const [counters, leadsByVertical, reached] = await Promise.all([
    counterTotals(range, people, vertical.id),
    leadsCreatedByVertical(range, people, vertical.id),
    reachedByStage(range, people, vertical.id),
  ])

  const funnel = buildFunnel(
    vertical,
    counters,
    leadsByVertical.get(vertical.id) ?? 0,
    reached,
  )

  const lostStage = vertical.stages.find((stage) => stage.isLost)

  return {
    title: `${vertical.name} funnel`,
    subtitle:
      'Counters are dated by the day the work was logged; stage counts by the day the transition happened, and each is leads that ever passed through that stage rather than leads sitting there now.',
    meta: [
      [
        'Period',
        `${formatCounterDate(range.from)} to ${formatCounterDate(range.to)}`,
      ],
      ['Vertical', vertical.name],
      ['Person', people.only ? 'Filtered' : 'Everyone in scope'],
    ],
    columns: [
      { header: 'Half', width: 16 },
      { header: 'Step', width: 30 },
      { header: 'Count', format: 'number' },
      { header: 'Conversion %', format: 'percent', width: 14 },
      { header: 'Of', width: 26 },
    ],
    rows: [
      ...funnel.above.map((step) => [
        'Above the line',
        step.label,
        step.value,
        step.conversion,
        step.conversionOf,
      ]),
      ...(funnel.bridge
        ? [
            [
              'Bridge',
              funnel.bridge.label,
              funnel.bridge.value,
              funnel.bridge.conversion,
              funnel.bridge.conversionOf,
            ],
          ]
        : []),
      ...funnel.below.map((step) => [
        'Below the line',
        step.label,
        step.value,
        step.conversion,
        step.conversionOf,
      ]),
      ...(lostStage
        ? [
            [
              'Outcome',
              lostStage.name,
              reached.get(lostStage.id) ?? 0,
              null,
              'Reported beside the funnel, not inside it',
            ],
          ]
        : []),
    ],
  }
}

/** The staffing report's three levels, flattened into one metric table. */
async function buildStaffingTable(
  viewer: CurrentUser,
  params: Params,
): Promise<ReportTable> {
  const filters = pickReportFilters(params)
  const range = resolveRange(filters)
  const people = await resolvePeople(viewer, filters)

  const [requirementStages, candidateStages] = await Promise.all([
    prisma.requirementStage.findMany({
      where: { isActive: true },
      select: { id: true, code: true, name: true },
      orderBy: { sortOrder: 'asc' },
    }),
    prisma.candidateStage.findMany({
      where: { isActive: true },
      select: { id: true, code: true, name: true },
      orderBy: { sortOrder: 'asc' },
    }),
  ])

  const profileSharedStageId = byCode(
    candidateStages,
    CANDIDATE_STAGE_CODES.profileShared,
  )

  const [totals, requirementReached, subReached, sourced, outcomes, activity] =
    await Promise.all([
      requirementTotals(range, people),
      requirementReachedByStage(range, people),
      subReachedByStage(range, people),
      candidatesSourced(range, people),
      interviewAndPlacementTotals(range, people),
      requirementsWithActivity(range, people, profileSharedStageId),
    ])

  const qualifiedId = byCode(requirementStages, REQUIREMENT_STAGE_CODES.qualified)
  const qualified = qualifiedId ? (requirementReached.get(qualifiedId) ?? 0) : 0

  const shared = reachedFor(
    subReached,
    candidateStages,
    CANDIDATE_STAGE_CODES.profileShared,
  )
  const shortlisted = reachedFor(
    subReached,
    candidateStages,
    CANDIDATE_STAGE_CODES.shortlisted,
  )
  const interviewScheduled = reachedFor(
    subReached,
    candidateStages,
    CANDIDATE_STAGE_CODES.interviewScheduled,
  )
  const interviewCompleted = reachedFor(
    subReached,
    candidateStages,
    CANDIDATE_STAGE_CODES.interviewCompleted,
  )
  const selected = reachedFor(
    subReached,
    candidateStages,
    CANDIDATE_STAGE_CODES.selected,
  )

  // Metric, unit, value — a shape docs/02 §4.7 is already written in, and the one
  // that survives being read in a spreadsheet without the units being guessed.
  const rows: ReportTable['rows'] = [
    ['Requirements received', 'requirements', totals.received, null],
    ['Qualified requirements', 'requirements', qualified, rate(qualified, totals.received)],
    ['Openings', 'positions', totals.openings, null],
    ['Positions filled', 'positions', totals.positionsFilled, rate(totals.positionsFilled, totals.openings)],
    ['Candidates sourced', 'people', sourced, null],
    ['Profiles shared', 'submissions', shared, null],
    ['Profiles shortlisted', 'submissions', shortlisted, rate(shortlisted, shared)],
    ['Interviews scheduled', 'submissions', interviewScheduled, rate(interviewScheduled, shortlisted)],
    ['Interviews held', 'rounds', outcomes.interviews, null],
    ['Selections', 'submissions', selected, rate(selected, interviewCompleted)],
    ['Placements', 'placements', outcomes.placements, rate(outcomes.placements, selected)],
    ['Requirements with a profile shared', 'requirements', activity.withProfileShared, rate(activity.withProfileShared, totals.received)],
    ['Requirements with a placement', 'requirements', activity.withPlacement, rate(activity.withPlacement, totals.received)],
    // The conversion belongs on the filled row: it is `filled ÷ (filled + lost)`,
    // the requirement conversion of docs/02 §5. Sitting on the lost row it read
    // as a loss rate and said the opposite of what it computed.
    [
      'Requirements filled',
      'requirements',
      totals.filled,
      rate(totals.filled, totals.filled + totals.lost),
    ],
    ['Requirements lost', 'requirements', totals.lost, null],
    ['Requirements cancelled', 'requirements', totals.cancelled, null],
    ['Requirements still live', 'requirements', totals.open + totals.onHold, null],
  ]

  return {
    title: 'Staffing',
    subtitle:
      'Requirements are dated by the day they were raised, stage figures by the day the transition happened, and placements by the day the person joined. Requirement counts and submission counts are different units — the Unit column says which.',
    meta: [
      [
        'Period',
        `${formatCounterDate(range.from)} to ${formatCounterDate(range.to)}`,
      ],
      ['Person', people.only ? 'Filtered' : 'Everyone in scope'],
    ],
    columns: [
      { header: 'Metric', width: 34 },
      { header: 'Unit', width: 14 },
      { header: 'Value', format: 'number' },
      { header: 'Conversion %', format: 'percent', width: 14 },
    ],
    rows,
  }
}

/**
 * The narrowed dashboard, exported: one row, the viewer's own totals.
 *
 * Same loaders as the screen, so the file and the page cannot disagree. The
 * first column names the scope rather than a vertical, because that is what
 * the single row is: everything this person generated or owns, whichever
 * vertical it happens to sit in.
 */
async function buildOwnDashboard(scope: AnalyticsScope): Promise<ReportTable> {
  const [counts, pipeline, revenue, reached, meta] = await Promise.all([
    leadCounts(scope),
    pipelineValue(scope),
    revenueTotals(scope),
    reachedByCommonStage(scope),
    analyticsMeta(scope),
  ])

  return {
    title: 'Dashboard summary',
    subtitle:
      'Your own leads only: the ones you generated or own. Counts are leads created in the period, so Open + Won + Lost equals Total. Won revenue is booked in the period; Pending is as at today.',
    meta,
    columns: [
      { header: 'Scope', width: 22 },
      { header: 'Leads', format: 'number' },
      { header: 'Open', format: 'number' },
      { header: 'Won (cohort)', format: 'number', width: 14 },
      { header: 'Lost', format: 'number' },
      { header: 'Reached won in period', format: 'number', width: 20 },
      { header: 'Conversion %', format: 'percent', width: 14 },
      { header: 'Pipeline', format: 'money', width: 16 },
      { header: 'Won revenue', format: 'money', width: 16 },
      { header: 'Collected', format: 'money', width: 16 },
      { header: 'Pending', format: 'money', width: 16 },
    ],
    rows: [
      [
        'Your leads',
        counts.total,
        counts.open,
        counts.won,
        counts.lost,
        reached.get('WON') ?? 0,
        conversion(counts),
        pipeline.total,
        revenue.totals.won,
        revenue.totals.collected,
        revenue.totals.pending,
      ],
    ],
  }
}

/**
 * The dashboard itself, exported.
 *
 * Not one of the eleven reports, but the screen most likely to be forwarded, and
 * the KPI row is the part somebody wants in a slide. Same numbers, same loaders.
 */
async function buildDashboard(
  viewer: CurrentUser,
  params: Params,
): Promise<ReportTable> {
  // resolveDashboard, not resolveAnalytics: the screen counts only the viewer's
  // own leads unless they are an Admin, and an export that quietly used the
  // wider role scope would hand somebody a file that disagrees with the page it
  // was taken from. The eleven real reports keep the role scope.
  const scope = await resolveDashboard(viewer, params)

  // A narrowed dashboard has no cross-vertical breakdown on screen, so its
  // export must not have one either. Left as a row per vertical, the file
  // handed back the very table the page withholds: correct numbers in the
  // wrong shape, most rows structurally zero, and the fence defeated by the
  // button beside it. One row of their own totals is what the page shows.
  if (scope.ownOnly) return buildOwnDashboard(scope)

  const [rows, verticals, reachedWon, revenue, meta] = await Promise.all([
    groupedPerformance(scope, 'verticalId', ['WON']),
    verticalsWithStages(),
    reachedByVertical(scope, 'WON'),
    revenueTotals(scope),
    analyticsMeta(scope),
  ])

  const byKey = new Map(rows.map((row) => [row.key, row]))

  return {
    title: 'Dashboard summary',
    subtitle:
      'Counts are leads created in the period, so Open + Won + Lost equals Total. Won revenue is booked in the period; Pending is as at today.',
    meta,
    columns: [
      { header: 'Vertical', width: 22 },
      { header: 'Leads', format: 'number' },
      { header: 'Open', format: 'number' },
      { header: 'Won (cohort)', format: 'number', width: 14 },
      { header: 'Lost', format: 'number' },
      { header: 'Reached won in period', format: 'number', width: 20 },
      { header: 'Conversion %', format: 'percent', width: 14 },
      { header: 'Pipeline', format: 'money', width: 16 },
      { header: 'Won revenue', format: 'money', width: 16 },
      { header: 'Collected', format: 'money', width: 16 },
      { header: 'Pending', format: 'money', width: 16 },
    ],
    rows: verticals.map((vertical) => {
      const row = byKey.get(vertical.id)
      const money = revenue.byVertical.get(vertical.id)

      return [
        vertical.name,
        row?.counts.total ?? 0,
        row?.counts.open ?? 0,
        row?.counts.won ?? 0,
        row?.counts.lost ?? 0,
        reachedWon.get(vertical.id) ?? 0,
        row?.conversion ?? null,
        row?.pipeline ?? 0,
        row?.wonRevenue ?? 0,
        money?.collected ?? 0,
        money?.pending ?? 0,
      ]
    }),
  }
}

export const REPORT_REGISTRY: Record<string, ReportDefinition> = {
  dashboard: {
    key: 'dashboard',
    title: 'Dashboard summary',
    permission: PERMISSIONS.LEAD_VIEW,
    basename: 'dashboard',
    build: buildDashboard,
  },
  vertical: {
    key: 'vertical',
    title: 'Vertical performance',
    permission: PERMISSIONS.REPORT_VIEW,
    basename: 'vertical-performance',
    build: buildVertical,
  },
  'lead-source': {
    key: 'lead-source',
    title: 'Lead source performance',
    permission: PERMISSIONS.REPORT_VIEW,
    basename: 'lead-source-performance',
    build: buildLeadSource,
  },
  bde: {
    key: 'bde',
    title: 'BDE lead generation',
    permission: PERMISSIONS.REPORT_PERFORMANCE,
    basename: 'bde-lead-generation',
    build: buildBde,
  },
  bdm: {
    key: 'bdm',
    title: 'BDM conversion',
    permission: PERMISSIONS.REPORT_PERFORMANCE,
    basename: 'bdm-conversion',
    build: buildBdm,
  },
  aging: {
    key: 'aging',
    title: 'Pipeline aging',
    permission: PERMISSIONS.REPORT_VIEW,
    basename: 'pipeline-aging',
    build: buildAging,
  },
  'won-lost': {
    key: 'won-lost',
    title: 'Won / lost analysis',
    permission: PERMISSIONS.REPORT_VIEW,
    basename: 'won-lost-analysis',
    build: buildWonLost,
  },
  revenue: {
    key: 'revenue',
    title: 'Revenue',
    permission: PERMISSIONS.REPORT_REVENUE,
    basename: 'revenue',
    build: buildRevenue,
  },
  payments: {
    key: 'payments',
    title: 'Payment status',
    permission: PERMISSIONS.REPORT_REVENUE,
    basename: 'payment-status',
    build: buildPayments,
  },
  'product-demos': {
    key: 'product-demos',
    title: 'Product demos',
    permission: PERMISSIONS.REPORT_VIEW,
    basename: 'product-demos',
    build: buildDemos,
  },
  funnel: {
    key: 'funnel',
    title: 'Vertical funnel',
    permission: PERMISSIONS.REPORT_VIEW,
    basename: 'vertical-funnel',
    build: buildFunnelTable,
  },
  staffing: {
    key: 'staffing',
    title: 'Staffing',
    permission: PERMISSIONS.REPORT_VIEW,
    basename: 'staffing',
    build: buildStaffingTable,
  },
}

/** Common-stage labels for any export that names a bucket. */
export { COMMON_STAGE_LABELS }
