/**
 * The one shape every report hands to an exporter.
 *
 * README §29 asks for Excel and PDF on every report as well as the CSV the lists
 * already had. Three formats times eleven reports is thirty-three places for an
 * export to stop matching the screen it came from, so instead each report
 * produces *one* table — headers, typed cells and the filters it was run under —
 * and the three writers in `export.ts` render that. Adding a twelfth report costs
 * one loader; adding a fourth format costs one writer.
 *
 * Cells stay typed rather than pre-formatted. A money column written as the
 * string "$12,500" is a column nobody can sum in Excel, and a percentage written
 * as "12.4%" sorts as text — which puts 9% after 12%. So the value goes in as a
 * number and the column says what it is; each writer then formats for its own
 * medium. `null` is the empty cell, and reads as an em dash on screen and in the
 * PDF rather than as a zero, because "no invoices" and "nothing owed" are
 * different facts.
 */

export type CellFormat = 'text' | 'number' | 'money' | 'percent' | 'date'

export type ReportColumn = {
  header: string
  format?: CellFormat
  /** Character width hint for Excel and the PDF's column proportions. */
  width?: number
}

export type Cell = string | number | Date | null

export type ReportTable = {
  /** The report's name, used in the file name, the sheet and the PDF heading. */
  title: string
  /** What the numbers mean — the caveat the screen carries, carried into the file. */
  subtitle?: string
  columns: ReportColumn[]
  rows: Cell[][]
  /** A totals row, rendered bold and frozen out of any sort. */
  footer?: Cell[]
  /** "Period", "Vertical", "Generated by" — the filter set, as label/value pairs. */
  meta?: Array<[string, string]>
}

/**
 * The same table with every money column removed.
 *
 * The screens gate their money on `report.revenue` — a BDE sees leads and
 * conversions, not deal values. An export that carried the amounts anyway would
 * be a way around the permission, so the export route strips them for a viewer
 * who does not hold it. The revenue and payments reports need no stripping: the
 * whole report sits behind that permission, so the route never reaches them.
 *
 * A note is appended to the subtitle rather than the columns quietly vanishing,
 * because a spreadsheet with a column missing looks like a broken export.
 */
export function withoutMoney(table: ReportTable): ReportTable {
  const keep = table.columns
    .map((column, index) => ({ column, index }))
    .filter((entry) => entry.column.format !== 'money')

  if (keep.length === table.columns.length) return table

  const pick = (row: Cell[]): Cell[] => keep.map((entry) => row[entry.index] ?? null)

  return {
    ...table,
    subtitle: `${table.subtitle ? `${table.subtitle} ` : ''}Amount columns are omitted: they need the revenue-reporting permission.`,
    columns: keep.map((entry) => entry.column),
    rows: table.rows.map(pick),
    footer: table.footer ? pick(table.footer) : undefined,
  }
}

export const REPORT_FORMATS = ['csv', 'xlsx', 'pdf'] as const
export type ReportFormat = (typeof REPORT_FORMATS)[number]

export function isReportFormat(value: string | null): value is ReportFormat {
  return value !== null && (REPORT_FORMATS as readonly string[]).includes(value)
}

/**
 * A cell as text — for CSV and the PDF, both of which are strings all the way
 * down. Excel keeps the number and formats it in the cell instead.
 */
export function cellText(
  value: Cell,
  format: CellFormat = 'text',
  currency = '$',
): string {
  if (value === null || value === undefined || value === '') return '—'

  if (value instanceof Date) {
    return value.toLocaleDateString('en-GB', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
    })
  }

  if (typeof value === 'number') {
    if (format === 'money') {
      return `${currency}${value.toLocaleString('en-GB', {
        minimumFractionDigits: 0,
        maximumFractionDigits: 2,
      })}`
    }
    if (format === 'percent') return `${value.toFixed(1)}%`
    return value.toLocaleString('en-GB')
  }

  return String(value)
}

/** The Excel number format for a column, or undefined for plain text. */
export function excelFormat(
  format: CellFormat | undefined,
  currency: string,
): string | undefined {
  switch (format) {
    case 'money':
      // The symbol is escaped so a currency set to a letter — "R", say — is not
      // read by Excel as a format code.
      return `"${currency}"#,##0.00`
    case 'percent':
      // Stored as 12.4 rather than 0.124: the report's own arithmetic produces a
      // percentage, and multiplying by a hundred in one place and dividing in
      // another is how the two disagree.
      return '0.0"%"'
    case 'number':
      return '#,##0'
    case 'date':
      return 'dd mmm yyyy'
    default:
      return undefined
  }
}
